apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::828563240244:role/eksctl-fsnd-nodegroup-ng-c2148f65-NodeInstanceRole-16UAF5PTIQBKB
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::828563240244:role/FSNDFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-16T21:50:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1592"
  uid: 50774181-673c-4a0f-8e30-b9f2c0b09b35
